name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ "11.0" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: buildExtension
      - name: Upload extension
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: dist/*.zip
